# TP MIAGE conception logicielle

NOTE: TP de deux slots de 1h20

## Nom des étudiants de ce binôme 
WARNING: NE PAS OUBLIER DE MENTIONNER LES DEUX NOMS !

#XXX# et #YYY#

Commentaires éventuels des étudiants : #XXXXXX#


## Pré-requis 

WARNING: A faire impérativement *AVANT* le TP, nous n'aurons pas le temps pendant !

* disposer d'au moins un compte Github par binôme ;
* apporter au moins un portable Linux, MacOS ou Microsoft Windows par binôme ;
* un JDK 8+  (conseillé : OpenJdk. Sous linux, installer le paquet `openjdk-13-jdk` par exemple) ;
* Eclipse 2019+ installé avec le plugin 'DBeaver IDE' ;
* un démon Docker récent 2018+ ;
* disposer d'une image Docker postgresql en local, faire `docker pull postgres` ;
* un client REST (conseillés : https://insomnia.rest/[Insomnia] ou https://www.postman.com/[Postman]) ;
* forker sur Github le projet `bflorat/tp1-miage-2020` puis cloner votre dépôt Github dans votre workspace. Attention : *un seul fork par binôme*  ;
* importer dans Eclipse les projets `todolist-debut-ex1` et `todolist-debut-ex2`.

NOTE: Utiliser votre connexion Internet personnelle, pas le wifi de l'université (pour lequel il faut configurer le proxy HTTP)    

# Déroulement du TP

NOTE: [Rappel sur Git] Trois dépôts sont ici utilisés: le dépot Github de l'enseignant (`bflorat/tp1-miage-2020`), le dépot Github du binôme (`etudiant_x/tp1-miage-2020`), le dépot local sur le portable de l'un ou des deux étudiants du binôme.

NOTE: Pour importer un projet maven existant dans Eclipse, faire `File` -> `Import` -> `Import existing Maven project` et cocher le(s) projet(s) à importer.

Veuillez *répondre aux questions de la feuille de TP juste sous la question* (en modifiant, commitant puis poussant le fichier `README.adoc`).

Nous fournissons trois projets Eclipse servant de base de travail aux exercices suivant. Cela permet un point de synchronisation de tous les étudiants à différents moments du TP. 

# Exercice 1 - Finaliser une API Spring Boot
_Temps estimé : 1 h_

* Observer le code du projet `todolist-debut-ex1`

IMPORTANT: Que constatez-vous  en terme de découpage du code ? Imaginez un projet d'entreprise constitué de centaines de classes ainsi structuré. Que risque-t-il d'arriver ?

IMPORTANT: Que se passe-t-il si l'on renomme une colonne de la base de donnée ?

IMPORTANT: Où se trouve le code métier (voir la règle de gestion RG1) ? cette règle est-elle facilement testable par un test unitaire ? 

* Lancer une base PostgreSQL en Docker :
```bash
docker run --rm -it -e POSTGRES_PASSWORD=password -p 5432:5432 postgres
```
IMPORTANT: Expliquer cette ligne de commande (y compris les options utilisées)

* Compléter le code manquant dans la méthode `TodoListController.createTodoItem()`

* Pourquoi `todoItemRepository` est-il `null` ? Quelle est la meilleure façon de l'injecter ? Modifier le code en conséquence.

* Tester vos endpoints avec un client REST.


[NOTE]
====
* les endpoints sont donnés dans le contrôleur via les annotation `@XYZMapping` 
* Exemple de contenu JSON : 

```json
{
    "id": "0f8-06eb17ba8d34",
    "time": "2020-02-27T10:31:43Z",
    "content": "Faire les courses"
  }
```
====

* Quand les deux endpoints fonctionnent, faire un push vers Github et fermer le projet Eclipse (ne pas le supprimer).

# Exercice 2 - Découpage en couches


1) Réorganiser le code dans les couches standards. 

Faire en sorte par exemple que divers frontends puisse récupérer les mails. Nous aurons dans ce TP un seul frontend : un CLI (ligne de commande) qui sera implémenté sous la forme d'une classe `ClientMail` avec `main()`. 
Cette méthode main attend deux arguments : un booleen `production` qui précise si le mail doit vraiment être envoyé (`true`) ou si nous sommes en environnement de recette (`false`). Le second argument est le sujet du mail.

Rappel : exemple de méthode main qui parse un boolean : 
```
public static void main(String[] args) {
   production = Boolean.parseBoolean(args[0]);
   ...		
```
Conception :

![diag sequence](http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/bflorat/tp1-miage-2019/master/diag1.puml&ttt=1)
![diag classe](http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/bflorat/tp1-miage-2019/master/diag1.puml&ttt=1)

Prévoir une cinquième couche `commun` pour les éléments communs à toutes les couches comme les exceptions. 

`MailSender` est une interface, le choix de l'implémentation est fait par l'application en fonction de la valeur du booléen `production`.

# Exercice 3 - Injection de dépendances avec Guice
_Temps estimé : 20 mins_

Point de synchro : repartir du projet fourni `mailreader-ex3-ini`

Guice est le framework d'injection de dépendance en Java de Google. Il est léger et la configuration se fait en java (et non par fichier XML ou par annotations). Ses concurrents en Java sont principalement Spring Core et CDI dans le monde JEE. Ce pattern est également présent dans la plupart des languages, comme dans Symphony en PHP ou AngularJS en JavaScript.

La méthode `configure()` de la classe `MailReaderModule` contient la configuration de Guice. C'est ici qu'on associe une interface à la classe contrète qui sera injectée. Exemple :
```
bind(MonInterface.class).to(MaClasseConcrete.class)
```
Il est bien sûr également possible d'injecter des classes concrètes (comme ici le `MailService`).

1) Observer la méthode `ClientMail.main()` : elle charge la configuration et créé l'objet de haut niveau de l'arbre d'injection : un `InterpreteurLigneCommande`.

2) L'objet `InterpreteurLigneCommande` a besoin d'un `MailService`. Lui injecter (injection par constructeur) via l’annotation (standard java) `@Inject`.

3) Faire de même pour l'injection du `MailSender` dans le `MailService`.

4) Compléter la méthode `configure()` de la classe `MailReaderModule` pour spécifier l'implémentation de `MailSender` à injecter.


# Exercice 4 - TU
_Temps estimé : 30 mins_

1) Compléter les tests unitaires ou en écrire de nouveaux dans les test cases `MailTest` et `MailComparatorTest`. Enlever les annotations `@Ignore` s'il y en a.

2) Exécuter vos tests si besoin (automatique si vous pratiquez le test continu avec infinitest).

# Exercice 5 - BDD avec Cucumber-jvm
_Temps estimé : 40 mins_

Point de synchro : repartir du projet fourni `mailreader-ex5-ini`

cucumber-jvm est l'implémentation java de cucumber, un framework de BDD (Behavioral Driven Development) très populaire. Il est existe d'autres : JBehave (l'original, très similaire), Concordion, JGiven ...

Pour les besoins du TP, nous utilisons ici les notions de Scenario Outline, de Data Table et de Transformer permettant l'utilisation de données tabulaires et de formats custom. La syntaxe Cucumber/Gherkin est disponible ![ici](https://docs.cucumber.io/gherkin/reference/).

1) Compléter la classe `MailComparaisonStep`
2) Lancer le test `CucumberRunnerTest` en junit
3) Ouvrir dans un navigateur `target/cucumber/index.html`
4) Ajouter des cas de test dans la feature `trier_mail.feature`. Notez qu'aucun nouveau code n'a été nécessaire pour ajouter ces tests contrairement à un TU.
5) Ecrire un scenario simple au format textuel et les steps correspondants.

# Finalisation
Veuillez finaliser, vérifier votre code et vos réponses après le TP. Vous avez deux semaines avant cloture du projet.

# Cleanup
Si vous le désirez, vous pourrez supprimer votre projet github mais pas avant fin juin (noté)






http://localhost:8080/todos